# 原版
import torch
import torch.nn as nn
from mmcv.cnn import ConvModule
from mmengine.model import BaseModule
from mmrotate.models.builder import ROTATED_HEADS  # <-- CORRECTED IMPORT

from torch.nn import functional as F
import math
import einops
import torch
import torch.nn as nn

import math
import warnings
import torch.nn as nn
from mmcv.cnn import ConvModule

# Import the correct registry and the new base class
from mmrotate.models.builder import ROTATED_HEADS
from .convfc_rbbox_head import RotatedConvFCBBoxHead

def _trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    # Values are generated by using a truncated uniform distribution and
    # then using the inverse CDF for the normal distribution.
    # Get upper and lower cdf values
    l = norm_cdf((a - mean) / std)
    u = norm_cdf((b - mean) / std)

    # Uniformly fill tensor with values from [l, u], then translate to
    # [2l-1, 2u-1].
    tensor.uniform_(2 * l - 1, 2 * u - 1)

    # Use inverse cdf transform for normal distribution to get truncated
    # standard normal
    tensor.erfinv_()

    # Transform to proper mean, std
    tensor.mul_(std * math.sqrt(2.))
    tensor.add_(mean)

    # Clamp to ensure it's in the proper range
    tensor.clamp_(min=a, max=b)
    return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    NOTE: this impl is similar to the PyTorch trunc_normal_, the bounds [a, b] are
    applied while sampling the normal with mean/std applied, therefore a, b args
    should be adjusted to match the range of mean, std args.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    with torch.no_grad():
        return _trunc_normal_(tensor, mean, std, a, b)


import math
import einops
import torch
import torch.nn as nn


class LayerNormProxy(nn.Module):
    # copy from https://github.com/LeapLabTHU/DAT/blob/main/models/dat_blocks.py
    def __init__(self, dim):
        super().__init__()
        self.norm = nn.LayerNorm(dim)

    def forward(self, x):
        x = einops.rearrange(x, 'b c h w -> b h w c')
        x = self.norm(x)
        return einops.rearrange(x, 'b h w c -> b c h w')
    

class RountingFunction(nn.Module):

    def __init__(self, in_channels, kernel_number, dropout_rate=0.2, proportion=40.0):
        super().__init__()
        self.kernel_number = kernel_number
        self.dwc = nn.Conv2d(in_channels, in_channels, kernel_size=3, padding=1,
                             groups=in_channels, bias=False)
        self.norm = LayerNormProxy(in_channels)
        self.relu = nn.ReLU(inplace=True)

        self.avg_pool = nn.AdaptiveAvgPool2d((1, 1))

        self.dropout1 = nn.Dropout(dropout_rate)
        self.fc_alpha = nn.Linear(in_channels, kernel_number, bias=True)

        self.dropout2= nn.Dropout(dropout_rate)
        self.fc_theta = nn.Linear(in_channels, kernel_number, bias=False)

        self.act_func = nn.Softsign()
        self.proportion = proportion / 180.0 * math.pi
        
        # init weights
        trunc_normal_(self.dwc.weight, std=.02)
        trunc_normal_(self.fc_alpha.weight, std=.02)
        trunc_normal_(self.fc_theta.weight, std=.02)

    def forward(self, x):

        x = self.dwc(x)
        x = self.norm(x)
        x = self.relu(x)

        x = self.avg_pool(x).squeeze(dim=-1).squeeze(dim=-1)  # avg_x.shape = [batch_size, Cin]

        alphas = self.dropout1(x)
        alphas = self.fc_alpha(alphas)
        alphas = torch.sigmoid(alphas)

        angles = self.dropout2(x)
        angles = self.fc_theta(angles)
        angles = self.act_func(angles)
        angles = angles * self.proportion

        return alphas, angles

    def extra_repr(self):
        s = (f'kernel_number={self.kernel_number}')
        return s.format(**self.__dict__)


def _get_rotation_matrix(thetas):
    bs, g = thetas.shape
    device = thetas.device
    thetas = thetas.reshape(-1)  # [bs, n] --> [bs x n]
    
    x = torch.cos(thetas)
    y = torch.sin(thetas)
    x = x.unsqueeze(0).unsqueeze(0)  # shape = [1, 1, bs * g]
    y = y.unsqueeze(0).unsqueeze(0)
    a = x - y
    b = x * y
    c = x + y

    rot_mat_positive = torch.cat((
        torch.cat((a, 1-a, torch.zeros(1, 7, bs*g, device=device)), dim=1),
        torch.cat((torch.zeros(1, 1, bs*g, device=device), x-b, b, torch.zeros(1, 1, bs*g, device=device), 1-c+b, y-b, torch.zeros(1, 3, bs*g, device=device)), dim=1),
        torch.cat((torch.zeros(1, 2, bs*g, device=device), a, torch.zeros(1, 2, bs*g, device=device), 1-a, torch.zeros(1, 3, bs*g, device=device)), dim=1),
        torch.cat((b, y-b, torch.zeros(1,1 , bs*g, device=device), x-b, 1-c+b, torch.zeros(1, 4, bs*g, device=device)), dim=1),
        torch.cat((torch.zeros(1, 4, bs*g, device=device), torch.ones(1, 1, bs*g, device=device), torch.zeros(1, 4, bs*g, device=device)), dim=1),
        torch.cat((torch.zeros(1, 4, bs*g, device=device), 1-c+b, x-b, torch.zeros(1, 1, bs*g, device=device), y-b, b), dim=1),
        torch.cat((torch.zeros(1, 3, bs*g, device=device), 1-a, torch.zeros(1, 2, bs*g, device=device), a, torch.zeros(1, 2, bs*g, device=device)), dim=1),
        torch.cat((torch.zeros(1, 3, bs*g, device=device), y-b, 1-c+b, torch.zeros(1, 1, bs*g, device=device), b, x-b, torch.zeros(1, 1, bs*g, device=device)), dim=1),
        torch.cat((torch.zeros(1, 7, bs*g, device=device), 1-a, a), dim=1)
    ), dim=0)  # shape = [k^2, k^2, bs*g]

    rot_mat_negative = torch.cat((
        torch.cat((c, torch.zeros(1, 2, bs*g, device=device), 1-c, torch.zeros(1, 5, bs*g, device=device)), dim=1),
        torch.cat((-b, x+b, torch.zeros(1, 1, bs*g, device=device), b-y, 1-a-b, torch.zeros(1, 4, bs*g, device=device)), dim=1),
        torch.cat((torch.zeros(1, 1, bs*g, device=device), 1-c, c, torch.zeros(1, 6, bs*g, device=device)), dim=1),
        torch.cat((torch.zeros(1, 3, bs*g, device=device), x+b, 1-a-b, torch.zeros(1, 1, bs*g, device=device), -b, b-y, torch.zeros(1, 1, bs*g, device=device)), dim=1),
        torch.cat((torch.zeros(1, 4, bs*g, device=device), torch.ones(1, 1, bs*g, device=device), torch.zeros(1, 4, bs*g, device=device)), dim=1),
        torch.cat((torch.zeros(1, 1, bs*g, device=device), b-y, -b, torch.zeros(1, 1, bs*g, device=device), 1-a-b, x+b, torch.zeros(1, 3, bs*g, device=device)), dim=1),
        torch.cat((torch.zeros(1, 6, bs*g, device=device), c, 1-c, torch.zeros(1, 1, bs*g, device=device)), dim=1),
        torch.cat((torch.zeros(1, 4, bs*g, device=device), 1-a-b, b-y, torch.zeros(1, 1, bs*g, device=device), x+b, -b), dim=1),
        torch.cat((torch.zeros(1, 5, bs*g, device=device), 1-c, torch.zeros(1, 2, bs*g, device=device), c), dim=1)
    ), dim=0)  # shape = [k^2, k^2, bs*g]

    mask = (thetas >= 0).unsqueeze(0).unsqueeze(0)
    mask = mask.float()                                                   # shape = [1, 1, bs*g]
    rot_mat = mask * rot_mat_positive + (1 - mask) * rot_mat_negative     # shape = [k*k, k*k, bs*g]
    rot_mat = rot_mat.permute(2, 0, 1)                                    # shape = [bs*g, k*k, k*k]
    rot_mat = rot_mat.reshape(bs, g, rot_mat.shape[1], rot_mat.shape[2])  # shape = [bs, g, k*k, k*k]
    return rot_mat


def batch_rotate_multiweight(weights, lambdas, thetas):
    """
    Let
        batch_size = b
        kernel_number = n
        kernel_size = 3
    Args:
        weights: tensor, shape = [kernel_number, Cout, Cin, k, k]
        thetas: tensor of thetas,  shape = [batch_size, kernel_number]
    Return:
        weights_out: tensor, shape = [batch_size x Cout, Cin // groups, k, k]
    """
    assert(thetas.shape == lambdas.shape)
    assert(lambdas.shape[1] == weights.shape[0])

    b = thetas.shape[0]
    n = thetas.shape[1]
    k = weights.shape[-1]
    _, Cout, Cin, _, _ = weights.shape

    # Stage 1:
    # input: thetas: [b, n]
    #        lambdas: [b, n]
    # output: rotation_matrix: [b, n, 9, 9] (with gate) --> [b*9, n*9]

    #       Sub_Stage 1.1:
    #       input: [b, n] kernel
    #       output: [b, n, 9, 9] rotation matrix
    rotation_matrix = _get_rotation_matrix(thetas)

    #       Sub_Stage 1.2:
    #       input: [b, n, 9, 9] rotation matrix
    #              [b, n] lambdas
    #          --> [b, n, 1, 1] lambdas
    #          --> [b, n, 1, 1] lambdas dot [b, n, 9, 9] rotation matrix
    #          --> [b, n, 9, 9] rotation matrix with gate (done)
    #       output: [b, n, 9, 9] rotation matrix with gate
    lambdas = lambdas.unsqueeze(2).unsqueeze(3)
    rotation_matrix = torch.mul(rotation_matrix, lambdas)

    #       Sub_Stage 1.3: Reshape
    #       input: [b, n, 9, 9] rotation matrix with gate
    #       output: [b*9, n*9] rotation matrix with gate
    rotation_matrix = rotation_matrix.permute(0, 2, 1, 3)
    rotation_matrix = rotation_matrix.reshape(b*9, n*9)

    # Stage 2: Reshape 
    # input: weights: [n, Cout, Cin, 3, 3]
    #             --> [n, 3, 3, Cout, Cin]
    #             --> [n*9, Cout*Cin] done
    # output: weights: [n*9, Cout*Cin]
    weights = weights.permute(0, 3, 4, 1, 2)
    weights = weights.contiguous().view(n*9, Cout*Cin)


    # Stage 3: torch.mm
    # [b*9, n*9] x [n*9, Cout*Cin]
    # --> [b*9, Cout*Cin]
    rotation_matrix = rotation_matrix.to(weights.dtype)
    weights = weights.to(weights.dtype)
    weights = torch.mm(rotation_matrix, weights)
    

    # Stage 4: Reshape Back
    # input: [b*9, Cout*Cin]
    #    --> [b, 3, 3, Cout, Cin]
    #    --> [b, Cout, Cin, 3, 3]
    #    --> [b * Cout, Cin, 3, 3] done
    # output: [b * Cout, Cin, 3, 3]
    weights = weights.contiguous().view(b, 3, 3, Cout, Cin).to(torch.float)
    weights = weights.permute(0, 3, 4, 1, 2)
    weights = weights.reshape(b * Cout, Cin, 3, 3)

    return weights


class ARHead(nn.Module):

    def __init__(self, in_channels, out_channels, kernel_size=3,
                 stride=1, padding=1, dilation=1, groups=1, bias=False,
                 kernel_number=1, rounting_func=None, rotate_func=batch_rotate_multiweight):
        super().__init__()
        self.kernel_number = kernel_number
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding
        self.dilation = dilation
        self.groups = groups
        self.bias = bias

        self.rounting_func = RountingFunction(in_channels=in_channels, kernel_number=1)
        self.rotate_func = rotate_func

        self.weight = nn.Parameter(
            torch.Tensor(
                kernel_number, 
                out_channels,
                in_channels // groups,
                kernel_size,
                kernel_size,
            )
        )
        nn.init.kaiming_normal_(self.weight, mode='fan_out', nonlinearity='relu')

    def forward(self, x):
        # 1. Get rotation angles and weights for the entire batch
        # x shape: [bs, Cin, h, w]
        alphas, angles = self.rounting_func(x)

        # 2. Get the dynamically rotated kernels for the entire batch
        # rotated_weight shape: [bs * Cout, Cin, k, k]
        rotated_weight = self.rotate_func(self.weight, alphas, angles)

        # ⬇️ --- START: REPLACEMENT LOGIC FOR STABILITY --- ⬇️

        bs, Cin, h, w = x.shape
        Cout = self.out_channels

        # 3. Instead of reshaping the input, we process each sample in a loop.
        #    This is much more stable for PyTorch's autograd engine.

        # Split the input batch into a list of single samples.
        # x_split is a list of tensors, each with shape [1, Cin, H, W]
        x_split = torch.split(x, 1, dim=0)

        # Reshape and split the rotated weights to match the batch.
        # First, view it as [bs, Cout, Cin, k, k]
        rotated_weight = rotated_weight.view(bs, Cout, Cin, self.kernel_size, self.kernel_size)
        # Then, split into a list of weight tensors.
        # weight_split is a list of tensors, each with shape [1, Cout, Cin, k, k]
        weight_split = torch.split(rotated_weight, 1, dim=0)

        # 4. Apply convolution to each sample individually using its specific kernel.
        out_split = []
        for i in range(bs):
            single_x = x_split[i]                 # Shape: [1, Cin, H, W]
            single_weight = weight_split[i].squeeze(0) # Shape: [Cout, Cin, k, k]
            
            # Perform a standard 2D convolution for this single sample.
            single_out = F.conv2d(
                input=single_x, 
                weight=single_weight, 
                bias=None, 
                stride=self.stride, 
                padding=self.padding, 
                dilation=self.dilation, 
                groups=self.groups
            )
            out_split.append(single_out)

        # 5. Stack the results from the loop back into a single batch tensor.
        out = torch.cat(out_split, dim=0) # Final shape: [bs, Cout, H_out, W_out]
        
        # ⬆️ --- END: REPLACEMENT LOGIC --- ⬆️

        return out

    def extra_repr(self):
        s = ('{in_channels}, {out_channels}, kernel_number={kernel_number}'
             ', kernel_size={kernel_size}, stride={stride}, bias={bias}')
             
        if self.padding != (0,) * len(self.padding if isinstance(self.padding, tuple) else [self.padding]):
            s += ', padding={padding}'
        if self.dilation != (1,) * len(self.dilation if isinstance(self.dilation, tuple) else [self.dilation]):
            s += ', dilation={dilation}'
        if self.groups != 1:
            s += ', groups={groups}'
        return s.format(**self.__dict__)
    
    

@ROTATED_HEADS.register_module()
class HAPHead(RotatedConvFCBBoxHead): # <-- KEY CHANGE: Inherit from RotatedConvFCBBoxHead
    """
    Hybrid Angle Prediction Head (HAPHead).
    This version correctly handles convolutional features by inheriting from
    RotatedConvFCBBoxHead.
    """
    def __init__(self, num_convs=2, **kwargs):
        # Pass all arguments up to the parent class.
        # The parent will handle 'in_channels', 'conv_out_channels', etc.
        super().__init__(
            num_shared_convs=0,
            num_shared_fcs=0,
            num_cls_convs=num_convs,
            num_reg_convs=num_convs,
            **kwargs)

        # Now, build your custom ARHead layer
        # `self.in_channels` and `self.conv_out_channels` are now
        # available because the parent class's __init__ set them.
        self.coarse_alignment_conv = ARHead(
            self.in_channels,
            self.conv_out_channels,
            kernel_size=3,
            padding=1
        )
        
        # Override the parent's conv layers with our custom ones
        # The parent class has `self.cls_convs` and `self.reg_convs`
        # We will use these as our refinement layers.
        # The parent's `__init__` already built them for us.

    def forward(self, x):
        # 1. Coarse alignment of features using our custom ARHead
        # The output of RoIExtractor `x` is (num_rois, C, H, W)
        aligned_feat = self.coarse_alignment_conv(x)
        
        # 2. Refine the aligned features using the parent's conv layers
        # The RotatedConvFCBBoxHead's forward method expects to do this,
        # but we can call the layers directly to show the logic.
        cls_feat = aligned_feat
        reg_feat = aligned_feat

        for conv in self.cls_convs:
            cls_feat = conv(cls_feat)
        for conv in self.reg_convs:
            reg_feat = conv(reg_feat)

        # After the convs, the parent class flattens the features and uses FC layers
        # We need to call the parent's forward method to complete the process
        # starting from the point after the convolutions.
        # To do this, we call the parent's `forward` but pass our processed features.
        
        # The parent class's `forward` handles the FC layers and predictions.
        # To reuse it, we need to let it run its course. The easiest way
        # is to override the conv part and then call the parent's forward.
        # But for simplicity, let's just use the final layers from the parent.
        
        # Flatten the features for the FC layers
        if self.with_avg_pool:
            cls_feat = self.avg_pool(cls_feat)
            reg_feat = self.avg_pool(reg_feat)

        cls_feat = cls_feat.flatten(1)
        reg_feat = reg_feat.flatten(1)
        
        # Apply FC layers (which are defined in the parent class)
        for fc in self.shared_fcs:
            cls_feat = self.relu(fc(cls_feat))
            reg_feat = self.relu(fc(reg_feat))

        cls_score = self.fc_cls(cls_feat)
        bbox_pred = self.fc_reg(reg_feat)

        return cls_score, bbox_pred


# 轻量化1
# import torch
# import torch.nn as nn
# from mmcv.cnn import ConvModule
# from mmengine.model import BaseModule
# from mmrotate.models.builder import ROTATED_HEADS  # <-- CORRECTED IMPORT

# from torch.nn import functional as F
# import math
# import einops
# import torch
# import torch.nn as nn

# import math
# import warnings
# import torch.nn as nn
# from mmcv.cnn import ConvModule

# # Import the correct registry and the new base class
# from mmrotate.models.builder import ROTATED_HEADS
# from .convfc_rbbox_head import RotatedConvFCBBoxHead

# def _trunc_normal_(tensor, mean, std, a, b):
#     def norm_cdf(x):
#         return (1. + math.erf(x / math.sqrt(2.))) / 2.
#     if (mean < a - 2 * std) or (mean > b + 2 * std):
#         warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_.", stacklevel=2)
#     l = norm_cdf((a - mean) / std)
#     u = norm_cdf((b - mean) / std)
#     tensor.uniform_(2 * l - 1, 2 * u - 1)
#     tensor.erfinv_()
#     tensor.mul_(std * math.sqrt(2.))
#     tensor.add_(mean)
#     tensor.clamp_(min=a, max=b)
#     return tensor

# def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
#     with torch.no_grad():
#         return _trunc_normal_(tensor, mean, std, a, b)

# class LayerNormProxy(nn.Module):
#     def __init__(self, dim):
#         super().__init__()
#         self.norm = nn.LayerNorm(dim)
#     def forward(self, x):
#         x = einops.rearrange(x, 'b c h w -> b h w c')
#         x = self.norm(x)
#         return einops.rearrange(x, 'b h w c -> b c h w')

# class RountingFunction(nn.Module):
#     def __init__(self, in_channels, kernel_number, dropout_rate=0.2, proportion=40.0):
#         super().__init__()
#         self.kernel_number = kernel_number
#         self.dwc = nn.Conv2d(in_channels, in_channels, kernel_size=3, padding=1, groups=in_channels, bias=False)
#         self.norm = LayerNormProxy(in_channels)
#         self.relu = nn.ReLU(inplace=True)
#         self.avg_pool = nn.AdaptiveAvgPool2d((1, 1))
#         self.dropout1 = nn.Dropout(dropout_rate)
#         self.fc_alpha = nn.Linear(in_channels, kernel_number, bias=True)
#         self.dropout2 = nn.Dropout(dropout_rate)
#         self.fc_theta = nn.Linear(in_channels, kernel_number, bias=False)
#         self.act_func = nn.Softsign()
#         self.proportion = proportion / 180.0 * math.pi
#         trunc_normal_(self.dwc.weight, std=.02)
#         trunc_normal_(self.fc_alpha.weight, std=.02)
#         trunc_normal_(self.fc_theta.weight, std=.02)
#     def forward(self, x):
#         x_feat = self.dwc(x)
#         x_feat = self.norm(x_feat)
#         x_feat = self.relu(x_feat)
#         x_feat = self.avg_pool(x_feat).squeeze(dim=-1).squeeze(dim=-1)
#         alphas = torch.sigmoid(self.fc_alpha(self.dropout1(x_feat)))
#         angles = self.act_func(self.fc_theta(self.dropout2(x_feat))) * self.proportion
#         return alphas, angles


# # ==============================================================================
# # 2. 核心模块: LightweightARConv (包含错误修复)
# # ==============================================================================

# class LightweightARConv(nn.Module):
#     """
#     究极轻量化版本的主动旋转卷积 (Lightweight Active-Rotating Convolution).
#     """
#     def __init__(self, in_channels, out_channels, kernel_size=3,
#                  stride=1, padding=1, kernel_number=4):
#         super().__init__()
#         assert kernel_size == 3, "This implementation is optimized for 3x3 kernels."
#         self.in_channels = in_channels
#         self.out_channels = out_channels
#         self.stride = stride
#         self.padding = padding
#         self.kernel_number = kernel_number

#         self.rounting_func = RountingFunction(in_channels, kernel_number)
#         self.base_dw_kernels = nn.Parameter(
#             torch.randn(self.kernel_number, self.in_channels, kernel_size, kernel_size)
#         )
#         nn.init.kaiming_normal_(self.base_dw_kernels, mode='fan_out', nonlinearity='relu')
#         self.pointwise_conv = nn.Conv2d(in_channels, out_channels, kernel_size=1, bias=False)
#         self.norm = nn.BatchNorm2d(out_channels)
#         self.relu = nn.ReLU(inplace=True)

#     def _rotate_kernels(self, kernels, angles):
#         """
#         使用 F.grid_sample 高效地旋转卷积核。
#         - kernels: [N, C_in, k, k]
#         - angles: [B, N]
#         Returns: [B, N, C_in, k, k] 旋转后的卷积核
#         """
#         batch_size, n_kernels = angles.shape
        
#         # --- START: CORRECTED LOGIC ---
#         # 1. 准备卷积核张量以进行批处理旋转
#         # kernels: [N, C_in, 3, 3] -> [1, N, C_in, 3, 3]
#         kernels_expanded = kernels.unsqueeze(0)
#         # -> [B, N, C_in, 3, 3] 通过为批次中的每个样本重复B次
#         kernels_expanded = kernels_expanded.repeat(batch_size, 1, 1, 1, 1)
#         # -> [B * N, C_in, 3, 3] 以匹配仿射矩阵的批次维度
#         kernels_to_rotate = kernels_expanded.view(batch_size * n_kernels, self.in_channels, 3, 3)
#         # --- END: CORRECTED LOGIC ---

#         # 2. 准备仿射矩阵 (这部分逻辑是正确的)
#         thetas = angles.view(-1)
#         affine_matrices = torch.zeros(batch_size * n_kernels, 2, 3, device=kernels.device)
#         cos_t, sin_t = torch.cos(thetas), torch.sin(thetas)
#         affine_matrices[:, 0, 0] = cos_t
#         affine_matrices[:, 0, 1] = -sin_t
#         affine_matrices[:, 1, 0] = sin_t
#         affine_matrices[:, 1, 1] = cos_t
        
#         # 3. 生成网格，现在批次维度匹配了 (B*N)
#         grid = F.affine_grid(affine_matrices, kernels_to_rotate.size(), align_corners=True)

#         # 4. 应用旋转
#         rotated_kernels = F.grid_sample(kernels_to_rotate, grid, align_corners=True)
        
#         # 5. 重塑以供输出
#         return rotated_kernels.view(batch_size, n_kernels, self.in_channels, 3, 3)

#     def forward(self, x):
#         batch_size, _, h, w = x.shape
#         alphas, angles = self.rounting_func(x)
#         rotated_dw_kernels = self._rotate_kernels(self.base_dw_kernels, angles)
        
#         alphas_reshaped = alphas.view(batch_size, self.kernel_number, 1, 1, 1)
#         weighted_kernels = rotated_dw_kernels * alphas_reshaped
#         final_dw_kernel = torch.sum(weighted_kernels, dim=1)
        
#         x_grouped = x.view(1, batch_size * self.in_channels, h, w)
#         kernel_grouped = final_dw_kernel.view(batch_size * self.in_channels, 1, 3, 3)
        
#         out = F.conv2d(x_grouped, kernel_grouped, stride=self.stride, padding=self.padding, groups=batch_size * self.in_channels)
#         out = out.view(batch_size, self.in_channels, out.shape[-2], out.shape[-1])
        
#         out = self.pointwise_conv(out)
#         out = self.relu(self.norm(out))
#         return out

# # ==============================================================================
# # 3. 最终的头部定义: LightweightHAPHead
# # ==============================================================================

# @ROTATED_HEADS.register_module()
# class HAPHead(RotatedConvFCBBoxHead):
#     """
#     集成了 LightweightARConv 的究极轻量化HAPHead。
#     """
#     def __init__(self, num_convs=2, kernel_number=4, **kwargs):
#         super().__init__(
#             num_shared_convs=0, num_shared_fcs=0,
#             num_cls_convs=num_convs, num_reg_convs=num_convs, **kwargs)

#         self.coarse_alignment_conv = LightweightARConv(
#             self.in_channels, self.conv_out_channels, kernel_number=kernel_number)
        
#         self.cls_convs = self._build_lightweight_convs(num_convs)
#         self.reg_convs = self._build_lightweight_convs(num_convs)

#     def _build_lightweight_convs(self, num_convs):
#         """辅助函数，构建深度可分离卷积层列表"""
#         convs = nn.ModuleList()
#         channels = self.conv_out_channels 
#         for i in range(num_convs):
#             layer = nn.Sequential(
#                 nn.Conv2d(channels, channels, kernel_size=3, padding=1, groups=channels, bias=False),
#                 nn.Conv2d(channels, channels, kernel_size=1, bias=False),
#                 nn.BatchNorm2d(channels),
#                 nn.ReLU(inplace=True))
#             convs.append(layer)
#         return convs

#     def forward(self, x):
#         aligned_feat = self.coarse_alignment_conv(x)
#         cls_feat, reg_feat = aligned_feat, aligned_feat
#         for conv in self.cls_convs:
#             cls_feat = conv(cls_feat)
#         for conv in self.reg_convs:
#             reg_feat = conv(reg_feat)

#         if self.with_avg_pool:
#             cls_feat, reg_feat = self.avg_pool(cls_feat), self.avg_pool(reg_feat)
#         cls_feat, reg_feat = cls_feat.flatten(1), reg_feat.flatten(1)
#         for fc in self.shared_fcs:
#             cls_feat, reg_feat = self.relu(fc(cls_feat)), self.relu(fc(reg_feat))
#         cls_score, bbox_pred = self.fc_cls(cls_feat), self.fc_reg(reg_feat)

#         return cls_score, bbox_pred


# # #轻量化2
# import torch
# import torch.nn as nn
# from mmcv.cnn import ConvModule
# from mmengine.model import BaseModule
# from mmrotate.models.builder import ROTATED_HEADS  # <-- CORRECTED IMPORT

# from torch.nn import functional as F
# import math
# import einops
# import torch
# import torch.nn as nn

# import math
# import warnings
# import torch.nn as nn
# from mmcv.cnn import ConvModule

# # Import the correct registry and the new base class
# from mmrotate.models.builder import ROTATED_HEADS
# from .convfc_rbbox_head import RotatedConvFCBBoxHead

# def _trunc_normal_(tensor, mean, std, a, b):
#     def norm_cdf(x):
#         return (1. + math.erf(x / math.sqrt(2.))) / 2.
#     if (mean < a - 2 * std) or (mean > b + 2 * std):
#         warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_.", stacklevel=2)
#     l = norm_cdf((a - mean) / std)
#     u = norm_cdf((b - mean) / std)
#     tensor.uniform_(2 * l - 1, 2 * u - 1)
#     tensor.erfinv_()
#     tensor.mul_(std * math.sqrt(2.))
#     tensor.add_(mean)
#     tensor.clamp_(min=a, max=b)
#     return tensor

# def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
#     with torch.no_grad():
#         return _trunc_normal_(tensor, mean, std, a, b)

# class LayerNormProxy(nn.Module):
#     def __init__(self, dim):
#         super().__init__()
#         self.norm = nn.LayerNorm(dim)
#     def forward(self, x):
#         x = einops.rearrange(x, 'b c h w -> b h w c')
#         x = self.norm(x)
#         return einops.rearrange(x, 'b h w c -> b c h w')

# class RountingFunction(nn.Module):
#     def __init__(self, in_channels, dropout_rate=0.2, proportion=90.0):
#         super().__init__()
#         self.dwc = nn.Conv2d(in_channels, in_channels, kernel_size=3, padding=1, groups=in_channels, bias=False)
#         self.norm = LayerNormProxy(in_channels)
#         self.relu = nn.ReLU(inplace=True)
#         self.avg_pool = nn.AdaptiveAvgPool2d((1, 1))
#         self.dropout = nn.Dropout(dropout_rate)
#         self.fc_theta = nn.Linear(in_channels, 1, bias=False)
#         self.act_func = nn.Tanh()
#         self.proportion = proportion / 180.0 * math.pi
#         trunc_normal_(self.dwc.weight, std=.02)
#         trunc_normal_(self.fc_theta.weight, std=.02)
#     def forward(self, x):
#         x_feat = self.dwc(x)
#         x_feat = self.norm(x_feat)
#         x_feat = self.relu(x_feat)
#         x_feat = self.avg_pool(x_feat).squeeze(dim=-1).squeeze(dim=-1)
#         angles = self.act_func(self.fc_theta(self.dropout(x_feat))) * self.proportion
#         return angles.squeeze(-1)

# # ==============================================================================
# # 2. 最终的头部定义: HAPHead (使用 AngleAlignedHead 的逻辑)
# # ==============================================================================

# @ROTATED_HEADS.register_module()
# class HAPHead(RotatedConvFCBBoxHead):
#     """
#     角度对齐头部 (Angle-Aligned Head).
#     """
#     def __init__(self, num_convs=2, **kwargs):
#         super().__init__(
#             num_shared_convs=0,
#             num_shared_fcs=0,
#             num_cls_convs=num_convs,
#             num_reg_convs=num_convs,
#             **kwargs)

#         self.angle_predictor = RountingFunction(self.in_channels)
#         self.convs = self._build_lightweight_convs(num_convs, self.in_channels, self.conv_out_channels)
        
#         if isinstance(self.roi_feat_size, int):
#             spatial_dim = self.roi_feat_size * self.roi_feat_size
#         elif isinstance(self.roi_feat_size, tuple):
#             spatial_dim = self.roi_feat_size[0] * self.roi_feat_size[1]
#         else:
#             raise TypeError(f"Unsupported type for roi_feat_size: {type(self.roi_feat_size)}")
        
#         feature_dim = self.conv_out_channels * spatial_dim
#         angle_feature_dim = 2
        
#         # --- START: CORRECTED CODE ---
#         # Manually calculate the output dimension for the regression head.
#         if self.reg_class_agnostic:
#             reg_out_channels = 5  # For (x, y, w, h, a)
#         else:
#             # self.num_classes is set by the parent class
#             reg_out_channels = 5 * self.num_classes
#         # --- END: CORRECTED CODE ---
        
#         self.fc_cls = nn.Linear(feature_dim, self.num_classes + 1)
#         self.fc_reg = nn.Linear(feature_dim + angle_feature_dim, reg_out_channels)


#     def _build_lightweight_convs(self, num_convs, in_channels, out_channels):
#         layers = []
#         for i in range(num_convs):
#             in_c = in_channels if i == 0 else out_channels
#             layer = nn.Sequential(
#                 nn.Conv2d(in_c, in_c, kernel_size=3, padding=1, groups=in_c, bias=False),
#                 nn.Conv2d(in_c, out_channels, kernel_size=1, bias=False),
#                 nn.BatchNorm2d(out_channels),
#                 nn.ReLU(inplace=True)
#             )
#             layers.append(layer)
#         return nn.Sequential(*layers)

#     def _rotate_features(self, features, angles):
#         batch_size = features.shape[0]
#         thetas = -angles
#         affine_matrices = torch.zeros(batch_size, 2, 3, device=features.device)
#         cos_t, sin_t = torch.cos(thetas), torch.sin(thetas)
#         affine_matrices[:, 0, 0] = cos_t
#         affine_matrices[:, 0, 1] = -sin_t
#         affine_matrices[:, 1, 0] = sin_t
#         affine_matrices[:, 1, 1] = cos_t
#         grid = F.affine_grid(affine_matrices, features.size(), align_corners=True)
#         rotated_features = F.grid_sample(features, grid, align_corners=True)
#         return rotated_features

#     def forward(self, x):
#         coarse_angle = self.angle_predictor(x)
#         x_aligned = self._rotate_features(x, coarse_angle)
#         conv_feat = self.convs(x_aligned)
#         feat_flattened = conv_feat.flatten(1)
#         cls_score = self.fc_cls(feat_flattened)
#         angle_feat = torch.stack([torch.sin(coarse_angle), torch.cos(coarse_angle)], dim=1)
#         reg_feat_fused = torch.cat([feat_flattened, angle_feat], dim=1)
#         bbox_pred = self.fc_reg(reg_feat_fused)
#         return cls_score, bbox_pred